export const SUCURSALES_DATA = [
  {
    usuario: "admin",
    ciudad: "Lima-Oficina",
    responsable: "Sergio",
    telefono: "51920544295",
    correo: "sergio.araujo@quetalcompra.com",
    pin: "7232",
    role: "admin",
    maneja_stock: false,
  },
  {
    usuario: "edwin",
    ciudad: "Lima",
    responsable: "Edwin Portilla",
    telefono: "",
    correo: "edwin.portilla@quetalcompra.com",
    pin: "1234",
    role: "admin",
    maneja_stock: false,
  },
  {
    usuario: "pedrito",
    ciudad: "Lima",
    responsable: "Pedro Benites",
    telefono: "",
    correo: "pedro.benites@quetalcompra.com",
    pin: "1234",
    role: "admin",
    maneja_stock: false,
  },
  {
    usuario: "anita",
    ciudad: "Lima",
    responsable: "Ana Heiland",
    telefono: "",
    correo: "ana.heiland@quetalcompra.com",
    pin: "1234",
    role: "admin",
    maneja_stock: false,
  },
];
