export const SUCURSALES_DATA = [
  {
    usuario: "admin",
    ciudad: "Lima-Oficina",
    responsable: "Sergio",
    telefono: "51920544295",
    correo: "sergio.araujo@quetalcompra.com",
    pin: "7232",
    role: "admin",
  },
  {
    usuario: "admin_oficina",
    ciudad: "Lima-Oficina",
    responsable: "Jesus",
    telefono: "51950499906",
    correo: "jesus.tapia@quetalcompra.com",
    pin: "7232",
    role: "admin",
  },
  {
    usuario: "admin_almacen",
    ciudad: "Lima-Almacen",
    responsable: "Wilber",
    telefono: "51991201398",
    correo: "wilber.mallma@quetalcompra.com",
    pin: "7232",
    role: "admin",
  },
  {
    usuario: "lima",
    ciudad: "Lima",
    responsable: "Gabriel",
    telefono: "51986885305",
    correo: "gabriel.castro@quetalcompra.com",
    pin: "1001",
    role: "sucursal",
  },
  {
    usuario: "chiclayo",
    ciudad: "Chiclayo",
    responsable: "Cesar",
    telefono: "51967143492",
    correo: "cesar.flores@quetalcompra.com",
    pin: "1002",
    role: "sucursal",
  },
  {
    usuario: "ica",
    ciudad: "Ica",
    responsable: "Victor",
    telefono: "51932819981",
    correo: "victor.vicerrel@quetalcompra.com",
    pin: "1003",
    role: "sucursal",
  },
  {
    usuario: "bellavista",
    ciudad: "Bellavista",
    responsable: "Jerson",
    telefono: "51980312074",
    correo: "jerson.silva@quetalcompra.com",
    pin: "1004",
    role: "sucursal",
  },
  {
    usuario: "nueva_cajamarca",
    ciudad: "Nueva Cajamarca",
    responsable: "Wilson",
    telefono: "51920766543",
    correo: "wilson.carhuancho@quetalcompra.com",
    pin: "1005",
    role: "sucursal",
  },
  {
    usuario: "pucallpa",
    ciudad: "Pucallpa",
    responsable: "Jhon",
    telefono: "51937163147",
    correo: "jhon.duendez@quetalcompra.com",
    pin: "1006",
    role: "sucursal",
  },
  {
    usuario: "jaen",
    ciudad: "Jaen",
    responsable: "Mariano",
    telefono: "51927341531",
    correo: "mariano.vega@quetalcompra.com",
    pin: "1007",
    role: "sucursal",
  },
  {
    usuario: "huanuco",
    ciudad: "Huanuco",
    responsable: "Nando",
    telefono: "51900706910",
    correo: "nando.martinez@quetalcompra.com",
    pin: "1008",
    role: "sucursal",
  },
  {
    usuario: "yurimaguas",
    ciudad: "Yurimaguas",
    responsable: "Percy",
    telefono: "51936066946",
    correo: "percy.saucedo@quetalcompra.com",
    pin: "1009",
    role: "sucursal",
  },
];
